[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'git-lfs']

[phases.install]
cmds = [
  'git lfs install',
  'git lfs pull',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'